linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - wsl
    - lll

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: td

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
  exclude-dirs:
    - bin
    - .github

run:
  timeout: 5m
  tests: true 
  # Using exclude-dirs in issues section instead of skip-dirs here 