// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Day struct {
	ID           int64
	Date         time.Time
	ShutdownTime time.Time
	DayGoal      string
	StartedAt    time.Time
	Rating       sql.NullInt64
	Reason       sql.NullString
	FocusHours   sql.NullFloat64
	FinishedAt   sql.NullTime
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Metadata struct {
	ID         int64
	PomoActive bool
}

type Pomodori struct {
	ID              int64
	StartTime       time.Time
	EndTime         sql.NullTime
	DurationMinutes int64
	Completed       sql.NullBool
	Tags            sql.NullString
	CreatedAt       sql.NullTime
}
