// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createDay = `-- name: CreateDay :one
INSERT INTO days (date, shutdown_time, day_goal, started_at)
VALUES (?, ?, ?, ?)
RETURNING id, date, shutdown_time, day_goal, started_at, rating, reason, focus_hours, finished_at, created_at, updated_at
`

type CreateDayParams struct {
	Date         time.Time
	ShutdownTime time.Time
	DayGoal      string
	StartedAt    time.Time
}

func (q *Queries) CreateDay(ctx context.Context, arg CreateDayParams) (Day, error) {
	row := q.db.QueryRowContext(ctx, createDay,
		arg.Date,
		arg.ShutdownTime,
		arg.DayGoal,
		arg.StartedAt,
	)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.ShutdownTime,
		&i.DayGoal,
		&i.StartedAt,
		&i.Rating,
		&i.Reason,
		&i.FocusHours,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePomodoro = `-- name: GetActivePomodoro :one
SELECT id, start_time, end_time, duration_minutes, completed, created_at FROM pomodori WHERE end_time IS NULL ORDER BY start_time DESC LIMIT 1
`

func (q *Queries) GetActivePomodoro(ctx context.Context) (Pomodori, error) {
	row := q.db.QueryRowContext(ctx, getActivePomodoro)
	var i Pomodori
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const getDayByDate = `-- name: GetDayByDate :one
SELECT id, date, shutdown_time, day_goal, started_at, rating, reason, focus_hours, finished_at, created_at, updated_at FROM days WHERE date = ?
`

func (q *Queries) GetDayByDate(ctx context.Context, date time.Time) (Day, error) {
	row := q.db.QueryRowContext(ctx, getDayByDate, date)
	var i Day
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.ShutdownTime,
		&i.DayGoal,
		&i.StartedAt,
		&i.Rating,
		&i.Reason,
		&i.FocusHours,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMetadata = `-- name: GetMetadata :one
SELECT id, pomo_active FROM metadata WHERE id = 1
`

func (q *Queries) GetMetadata(ctx context.Context) (Metadata, error) {
	row := q.db.QueryRowContext(ctx, getMetadata)
	var i Metadata
	err := row.Scan(&i.ID, &i.PomoActive)
	return i, err
}

const insertPomodoro = `-- name: InsertPomodoro :one
INSERT INTO pomodori (start_time, end_time, duration_minutes, completed)
VALUES (?, ?, ?, ?)
RETURNING id, start_time, end_time, duration_minutes, completed, created_at
`

type InsertPomodoroParams struct {
	StartTime       time.Time
	EndTime         sql.NullTime
	DurationMinutes int64
	Completed       sql.NullBool
}

func (q *Queries) InsertPomodoro(ctx context.Context, arg InsertPomodoroParams) (Pomodori, error) {
	row := q.db.QueryRowContext(ctx, insertPomodoro,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMinutes,
		arg.Completed,
	)
	var i Pomodori
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.DurationMinutes,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const listDays = `-- name: ListDays :many
SELECT id, date, shutdown_time, day_goal, started_at, rating, reason, focus_hours, finished_at, created_at, updated_at FROM days ORDER BY date DESC
`

func (q *Queries) ListDays(ctx context.Context) ([]Day, error) {
	rows, err := q.db.QueryContext(ctx, listDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Day
	for rows.Next() {
		var i Day
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.ShutdownTime,
			&i.DayGoal,
			&i.StartedAt,
			&i.Rating,
			&i.Reason,
			&i.FocusHours,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPomodori = `-- name: ListPomodori :many
SELECT id, start_time, end_time, duration_minutes, completed, created_at FROM pomodori ORDER BY start_time DESC
`

func (q *Queries) ListPomodori(ctx context.Context) ([]Pomodori, error) {
	rows, err := q.db.QueryContext(ctx, listPomodori)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pomodori
	for rows.Next() {
		var i Pomodori
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMinutes,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDayEnd = `-- name: UpdateDayEnd :exec
UPDATE days SET rating = ?, reason = ?, focus_hours = ?, finished_at = ? WHERE date = ?
`

type UpdateDayEndParams struct {
	Rating     sql.NullInt64
	Reason     sql.NullString
	FocusHours sql.NullFloat64
	FinishedAt sql.NullTime
	Date       time.Time
}

func (q *Queries) UpdateDayEnd(ctx context.Context, arg UpdateDayEndParams) error {
	_, err := q.db.ExecContext(ctx, updateDayEnd,
		arg.Rating,
		arg.Reason,
		arg.FocusHours,
		arg.FinishedAt,
		arg.Date,
	)
	return err
}

const updatePomoActive = `-- name: UpdatePomoActive :exec
UPDATE metadata SET pomo_active = ? WHERE id = 1
`

func (q *Queries) UpdatePomoActive(ctx context.Context, pomoActive bool) error {
	_, err := q.db.ExecContext(ctx, updatePomoActive, pomoActive)
	return err
}

const updatePomodoroEndTime = `-- name: UpdatePomodoroEndTime :exec
UPDATE pomodori SET end_time = ?, completed = ? WHERE id = ?
`

type UpdatePomodoroEndTimeParams struct {
	EndTime   sql.NullTime
	Completed sql.NullBool
	ID        int64
}

func (q *Queries) UpdatePomodoroEndTime(ctx context.Context, arg UpdatePomodoroEndTimeParams) error {
	_, err := q.db.ExecContext(ctx, updatePomodoroEndTime, arg.EndTime, arg.Completed, arg.ID)
	return err
}
